apiVersion: apps/v1
kind: Deployment
metadata:
    name: stress-gin
    labels:
        app: str-gin
spec:
    replicas: 1
    selector:
        matchLabels:
            app: str-gin
    template:
        metadata:
            labels:
                app: str-gin
        spec:
            containers:
            - name: str-gin
              image: kweisamx/gotest
              command: ["/root/gin-str"]
              ports: 
              - containerPort: 8888
---

apiVersion: v1
kind: Service
metadata: 
    labels:
        app: str-gin
    name: service-str-gin
spec:
    ports:
    - port: 8888
      protocol: TCP
      targetPort: 8888
      nodePort: 30001
    selector:
        app: str-gin
    type: NodePort
